name: Trigger Playwright Tests

on:
  push:
    branches:
      - main  # main 브랜치에 push가 발생할 때

jobs:
  trigger-playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook to Playwright repository
        run: |
          curl -X POST https://api.github.com/repos/sseung95/playwright-test/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -d '{"event_type":"run-tests"}'
